[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/user/*"
  to = "/user/index.html"
  status = 200

[[redirects]]
  from = "/page.html"
  to = "/page.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
